### ISSUE TITLE
typescript support

### ISSUE THREAD

**Issue by ashleygwilliams** [ashleygwilliams/wasm-pack#107]
take a `--typescript` flag to `wasm-bindgen` and add a `types` key to the `package.json`
http://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

**Comment by robertohuertasm** [comment]
How have you thought to approach this? Trying to automatically generate the typings via some tool like [dts-gen](https://github.com/Microsoft/dts-gen) (which by the way, it doesn't seem to be supporting es6 at the moment)? or maybe you have something else in mind? :wink:

**Comment by robertohuertasm** [comment]
oh! That's awesome! Indeed @ashleygwilliams message already talked about it. I didn't read it carefully and  read `wasm-pack` instead of `wasm-bindgen` 😱 

@mgattozzi many thanks for your clarification! 😃

**Comment by ashleygwilliams** [comment]
solved by #109
