### ISSUE TITLE
Apply Markdownlint to .md files

### ISSUE THREAD

**Issue by robertohuertasm** [ashleygwilliams/wasm-pack#110]
While reading the `.md` files I noticed they were not following any standard format. I know it's a minor issue but maybe we could consider using [Markdownlint](https://github.com/markdownlint/markdownlint) in order to format this kind of files.

**Comment by ashleygwilliams** [comment]
hey! i like the idea of running a link but i'm curious if we can automate it to make sure it's run on CI so we can enforce it! it looks like it's written in ruby so i'm a little nervous about requiring a ruby dep for contributors- is there something similar in the rust ecosystem that we could use?

**Comment by robertohuertasm** [comment]
You're right. I already thought about inforcing this tool and was not comfortable with the idea of making contributors to install some external dependency. For the record, I'm using a plugin in VSCode that lints the files as you write/read them, but I think that's not a valid solution neither.

I'll give it a try and look for a crate that maybe can help us with this.

Regarding the PR, feel free to close it if you feel it doesn't provide any value at the moment. I just like to follow some rules in terms of formatting when writing `markdown` files and felt absorved by the compulsion of filling a PR amending this 😜

**Comment by ashleygwilliams** [comment]
closing for the time being. would love a rust solution for this!
