### ISSUE TITLE
Wasm-pack doesn't generate all files

### ISSUE THREAD

**Issue by JinwookKim** [ashleygwilliams/wasm-pack#112]
I was following [the tutorial](https://rust-lang-nursery.github.io/rust-wasm/wasm-pack/introduction.html) and it mentions at the end that it will generate the a wasm file and a JS wrapper file. I have tried this on Mac and on Windows and it has not generated those files in either case. It compiled the code but it did not copy anything over to the `pkg` directory, except for the `package.json` and README file. 

Is there something I'm missing?

**Comment by JinwookKim** [comment]
@mgattozzi !!! It worked! The `cargo install -f wasm-bindgen-cli` fixed it for me!
I'm sorry about the dupe issue. I tried looking over all the issues to make sure it wasn't a dupe, but it seemed like I missed the 102 issue. 

Thank you so much for your help!

**Comment by mgattozzi** [comment]
Hey @JinwookKim I appreciate that you did look for it at least! You're not the first one and we're discussing in #115 how to fix this up. Glad it worked out!
