### ISSUE TITLE
Support building debug versions of packages.

### ISSUE THREAD

**Issue by clanehin** [ashleygwilliams/wasm-pack#126]
I had a personal need to generate a debug version of a package in my project and quickly implemented a --debug flag. It may require some bikesheddish discussion:

(1) --debug is the opposite of the flag used by cargo (--release). Usage is more obvious if the wasm-pack flag is identical to the already-familiary cargo flag, however switching to --release also changes the default behavior of wasm-pack.

(2) There's a --debug flag in wasm-bindgen that we might also hook into.

(3) Not sure if this is within the scope of wasm-pack.

**Comment by ashleygwilliams** [comment]
hi @clanehin - thanks for filing this! i'm not opposed to a feature like this- though i am curious to learn more about the use case you had to generate a debug version of a package- would you mind sharing?

**Comment by ashleygwilliams** [comment]
@clanehin thanks so much for sharing! i think i realy dig this and am gonna try to sneak it into today's release... :D
