### ISSUE TITLE
regression: wasm-pack init requires you pass a directory

### ISSUE THREAD

**Issue by jbolila** [ashleygwilliams/wasm-pack#136]
```bash
❯ strace -e trace=open -- wasm-pack init
open("/proc/sys/vm/overcommit_memory", O_RDONLY) = 3
open("/sys/kernel/mm/transparent_hugepage/enabled", O_RDONLY) = 3
open(".", O_WRONLY|O_CREAT|O_APPEND|O_CLOEXEC, 0666) = -1 EISDIR (Is a directory)
Is a directory (os error 21)
Caused by: Is a directory (os error 21)
+++ exited with 1 +++
```

I'm getting this error (with the release musl 0.3.0 or building it locally), on Debian.

`cargo test` passes all the tests locally.

**Comment by mgattozzi** [comment]
How are you trying to use this? `wasm-pack init` already expects you to have a rust project. What's likely happening is that it's checking the current directory for the `Cargo.toml` but can't find it.

**Comment by jbolila** [comment]
@mgattozzi thank you for your reply. It has a simple Cargo.toml with lib and dependencies as described in the readme file.

Would this  be enough to get it working?

```bash
cargo new wat --lib ;  cd wat
wasm-pack init
```

**Comment by ashleygwilliams** [comment]
welp! can confirm that this is true. i think this may be a bug and i'll be working on a fix now!

**Comment by ashleygwilliams** [comment]
workaround - run `wasm-pack init .` (can confirm this works, but this should not have to be what happened)
