### ISSUE TITLE
progress bars?

### ISSUE THREAD

**Issue by ashleygwilliams** [ashleygwilliams/wasm-pack#14]
some of the build steps, particularly the compilation step is a little long, it might be nice to have some progress bars? is there an efficient rust progress bar lib for the CLI? @killercup maybe you know?

**Comment by killercup** [comment]
I think you're going to like https://crates.io/crates/indicatif :)

**Comment by ashleygwilliams** [comment]
yay thank u @killercup <3<3

**Comment by HKalbasi** [comment]
Is a progress bar for wasm-opt step possible?
