### ISSUE TITLE
detect if cargo toml has cdylib

### ISSUE THREAD

**Issue by ashleygwilliams** [ashleygwilliams/wasm-pack#140]
this issue is reserved for someone who has not yet contributed to wasm-pack

<hr/>

in order to compile to wasm32-unknown-unknown, the user must put the following in their `Cargo.toml`:

```
[lib]
crate-type = ["cdylib"]
```

we have the ability to check this before we try to compile- to save the user some time and help remind them to do it!

we'll probably want to work on this in the `manifest.rs` file, and it might be similar to the `get_crate_name` function... [see here](https://github.com/ashleygwilliams/wasm-pack/blob/master/src/manifest.rs#L136)

**Comment by kedromelon** [comment]
i'd love to take a crack at this! this is exactly the step that tripped me up trying out wasm-pack at first 😅

**Comment by ashleygwilliams** [comment]
sounds great! let me know if you need any help @kedromelon
