### ISSUE TITLE
detect if cargo toml has wasm-bindgen dep

### ISSUE THREAD

**Issue by ashleygwilliams** [ashleygwilliams/wasm-pack#141]
this issue is reserved for someone who has not yet contributed to wasm-pack

<hr/>

in order to compile to wasm32-unknown-unknown, the user must put the following in their `Cargo.toml`:

```
[dependencies]
wasm-bindgen = "0.2"
```

we have the ability to check this before we try to compile- to save the user some time and help remind them to do it!

we'll probably want to work on this in the `manifest.rs` file, and it might be similar to the `get_crate_name` function... [see here](https://github.com/ashleygwilliams/wasm-pack/blob/master/src/manifest.rs#L136)

**Comment by robertohuertasm** [comment]
I'd love to tackle this if it's ok for you!

**Comment by ashleygwilliams** [comment]
@robertohuertasm you got it! let me know if you want any help!

**Comment by robertohuertasm** [comment]
Do I have to check the version? If that's the case, must "0.2" be the minimum version or it has to be fixed?

**Comment by ashleygwilliams** [comment]
@robertohuertasm i think for the moment we should just check that the dependency is present. the version portion is a bit more complicated and something we'll deal with when we resolve #146
