### ISSUE TITLE
refactor command.rs into per command modules

### ISSUE THREAD

**Issue by ashleygwilliams** [ashleygwilliams/wasm-pack#165]
command.rs is getting pretty big. let's refactor it into per command modules.

i'm gonna snag this one and probably do it as clean up right before the 0.4.0 release (assuming there are no objections to this refactor)

**Comment by mgattozzi** [comment]
No this is good was going to recommend doing this soon myself

**Comment by ashleygwilliams** [comment]
fixed by #182
