### ISSUE TITLE
Add nightly toolchain to commands

### ISSUE THREAD

**Issue by FreeMasen** [ashleygwilliams/wasm-pack#171]
Currently, unless the user has set cargo to use the nightly compiler, this project will fail in a somewhat unfriendly way.

Updating the rustup/cargo commands to account for this would be helpful.

`rustup target add wasm32-unknown-unknown --toolchain nightly`
`cargo +nightly build --target wasm32-unknown-unknown`

It may be helpful to check that the nightly toolchain is actually installed as well
`rustc +nightly -V` or similar.

**Comment by ashleygwilliams** [comment]
@FreeMasen this is an excellent suggestion! if you'd like to add it- we'd welcome a PR- otherwise i'll open this up to contributors!

**Comment by FreeMasen** [comment]
I should be able to knock that out tomorrow.
