### ISSUE TITLE
Steps 1 and 7 are missing

### ISSUE THREAD

**Issue by migerh** [ashleygwilliams/wasm-pack#178]
This is the output of wasm-pack right now (current master branch 460dade1dfe1e94b2, not including the fixed spinners):

```
| [2/9] Adding WASM target...
| [3/9] Compiling to WASM...
| [4/9] Creating a pkg directory...
| [5/9] Writing a package.json...
| :-) [WARN]: Field description is missing from Cargo.toml. It is not necessary, but recommended
| :-) [WARN]: Field repository is missing from Cargo.toml. It is not necessary, but recommended
| :-) [WARN]: Field license is missing from Cargo.toml. It is not necessary, but recommended
| [6/9] Copying over your README...
| :-) [WARN]: origin crate has no README
| [8/9] Installing WASM-bindgen...
| [9/9] Running WASM-bindgen...
| :-) Done in 50 seconds
| :-) Your WASM pkg is ready to publish at ../rust/gif/pkg.
```

Steps 1 and 7 are missing.

Step 1 is missing because the `Step` struct in progressbar.rs is initialized with `1` instead of `0`.
Step 7 is missing because during the execution of [`Init::step_check_create_type()`](https://github.com/ashleygwilliams/wasm-pack/blob/460dade1dfe1e94b28964749ffcd024945b84275/src/command.rs#L340) no step is emitted but step is incremented nonetheless in [`Init::process()`](https://github.com/ashleygwilliams/wasm-pack/blob/460dade1dfe1e94b28964749ffcd024945b84275/src/command.rs#L250).

**Comment by ashleygwilliams** [comment]
working on this in #180 thanks for filing this issue @migerh - it's super detailed and incredibly useful, so appreciated <3
