### ISSUE TITLE
Improve PoisonError conversion

### ISSUE THREAD

**Issue by migerh** [ashleygwilliams/wasm-pack#179]
PR #164  refactored the progressbar such that it now uses RwLocks which might be poisoned. A PoisonError is converted to an `error::Error` and handed over the error to the caller.

@mgattozzi already pointed out that there is room for improvement regarding the error conversion (right now we potentially lose information contained within the PoisonError) in comments https://github.com/ashleygwilliams/wasm-pack/pull/164#issuecomment-396712019 and https://github.com/ashleygwilliams/wasm-pack/pull/164#pullrequestreview-128122493. But PoisonError has a type parameter so it might be tricky.

**Comment by mgattozzi** [comment]
I suspect that since we use it with 2 different types I believe the solution is to just use the concrete types rather than a generic T now that I've had time to think about it. :smile:

**Comment by migerh** [comment]
Right now it would be four types in total then, I think:

* `LockResult<RwLockReadGuard<String>>`
* `LockResult<RwLockWriteGuard<String>>`
* `LockResult<RwLockReadGuard<ProgressBar>>`
* `LockResult<RwLockWriteGuard<ProgressBar>>`

But if the `ProgressBar` and `String` members would be factored out into something like `ProgressOutputState` and this were to be put into an `RwLock<ProgressOutputState>` these four types could be reduced to two :thinking:

**Comment by migerh** [comment]
It could also be worth looking into [parking_lot](https://crates.io/crates/parking_lot). This library apparently will release the locks when a thread panics instead of poisoning them.

**Comment by mgattozzi** [comment]
I'm totally okay with improved versions of the std for this kind of thing. :D

**Comment by migerh** [comment]
Then I'll take a look at parking_lot.

**Comment by ashleygwilliams** [comment]
closed by #187
