### ISSUE TITLE
Warn on all missing fields in Cargo.toml

### ISSUE THREAD

**Issue by mgattozzi** [ashleygwilliams/wasm-pack#43]
When using wasm-pack via `wasm-pack init` only one field at a time is output as to what's missing from the Cargo.toml file. It would be nicer if all the fields missing were printed out all at once!

**Comment by ashleygwilliams** [comment]
ah yes! great. the error handling is p garbage rn (#12). thanks for filing this!

**Comment by sebinsua** [comment]
I also found it difficult to know what it was telling me.

It would be good if it said something like "[ERROR] The following fields are missing from your `Cargo.toml`: repository, license"

I honestly thought that it was just giving me a warning, and spent 10 minutes ignoring the message, and wondering why it wasn't working... >_<

**Comment by ashleygwilliams** [comment]
@sebinsua - sorry you ran into that trouble. this is def a feature we are going to implement!

**Comment by mgattozzi** [comment]
Just put a PR in to fix this! :D
