### ISSUE TITLE
Installing wasm-bindgen tool is non obvious

### ISSUE THREAD

**Issue by mgattozzi** [ashleygwilliams/wasm-pack#46]
When first running wasm-pack there's no indication that wasm-bindgen is being installed at first. I had a huge spike in CPU usage and was confused why it happened the first time I ran the command. It wasn't until looking in the code for something that I saw why.

If this is the first time then we should print out that it will be compiled and installed. If it's not and it exists and the version is not outdated we should print out that it's already installed. If it's installed and outdated we should print out that we're updating it.

**Comment by ashleygwilliams** [comment]
now that i've merged #49 i'm curious if you think this is ok now? i've made it clear that one step is installing wasm-bindgen and i've filed #51 to eventually account for not taking that step if we don't need to

**Comment by mgattozzi** [comment]
@ashleygwilliams I'll need to run this tomorrow at some point. Will let you know!

**Comment by mgattozzi** [comment]
This looks good to me! I think we can definitely follow up with #51 now.
