### ISSUE TITLE
write a log with all the stout/sterr 

### ISSUE THREAD

**Issue by ashleygwilliams** [ashleygwilliams/wasm-pack#50]
#49 turned off all the stdout/err fwding. this output is still useful for debugging when people run into issues, so let's write it to a `wasm-pack-debug.log`

**Comment by mgattozzi** [comment]
Some clarifying questions:
- Where do we want to store this log? Linux, Windows, and OSX would likely have different places
- We also want to utilize the verbosity setting as well so we want it to be able to log to the CLI as well yes?

**Comment by ashleygwilliams** [comment]
re the location, i was thinking we'd copy what npm does which is a `wasmpack-debug.log` in the root of the pkg (in our case the crate, which is default `.` or whatever path is passed)

and yes yes, verbosity settings please

**Comment by mgattozzi** [comment]
Okay that sounds good to me. We should probably automatically add the log to the .gitignore if it's not already there so it doesn't get comitted.

cool so in terms of verbosity levels something like:

No flag = error, warn, info
-v = error, warn, info, debug
-vv =　error, warn, info, debug, trace

Do we want the log appended too by default or overwrite each time? I would think append with some kind of delimeter for each run

**Comment by data-pup** [comment]
I’d love to help out with this one 🙂 I can start looking into it this weekend!
