### ISSUE TITLE
Example usage documentation

### ISSUE THREAD

**Issue by mgattozzi** [ashleygwilliams/wasm-pack#63]
While my tutorial over on rust-wasm hasn't landed in the book yet it will soonish. However, we want people to be able to reference something a little less longform as well because sometimes all you need is a few words describing how to use the tool.

We should make docs that are short like the readme but explain things like using the scope flag etc. Also maybe even use asciinema to show some visual examples for people!

**Comment by mgattozzi** [comment]
The tutorial did land and is available [here](https://rust-lang-nursery.github.io/rust-wasm/wasm-pack/introduction.html). This is still open and is not too hard to document. If you're looking for an easy contribution that helps others this is it!

Will provide in depth mentoring instructions upon request. Things that need to be documented:

- [ ] wasm-pack init
- [ ] wasm-pack pack
- [ ] wasm-pack publish

As well as other optional flags such as:

- [ ] scope for wasm-pack init

**Comment by ashleygwilliams** [comment]
i'd also add the path argument to this list as well!

**Comment by mgattozzi** [comment]
I updated the list! :D

**Comment by data-pup** [comment]
I would love to help with this one :) I can start with the init command and move from there.

**Comment by mgattozzi** [comment]
Awesome @data-pup! Here's what you'll need to do:

- Create a folder called docs
- Create a file called init.md
- In that file type up some instructions on how it works
- You shoul also mention the scope flag and optional path argument for it as well

This should be a good start for this.

I think we can then possibly later include them in the source code for a rustdoc build. Since we're on nightly anyways for the forseeable future we can use the `doc_include feature` in another PR to include what you write up as docs :) That's a little outside the scope of this issue now so don't worry about it.

Once you've got a good basis put in a PR and we can polish it up then merge it :D

**Comment by data-pup** [comment]
Sounds good! Thank you for the instructions, I will get started on that today. I will follow up if I have any questions 🙂

**Comment by mgattozzi** [comment]
@data-pup Sweet! :D

**Comment by mgattozzi** [comment]
Hey @data-pup in case it wasn't clear it'll name the package as:
@HELLO/your_rust_package_name

**Comment by mgattozzi** [comment]
@data-pup made some great first steps. I think we could expand this out with gifs and things showing how to use it. Some people are more visual than text. Video tutorials might also be fun.

**Comment by data-pup** [comment]
Yeah! I was thinking about that too. I really like the gif in the readme, what was used to make that? Adding a gif demonstrating each command wouldn't be too hard :)

**Comment by mgattozzi** [comment]
@ashleygwilliams came up with it so she can probably explain what that process was

**Comment by ashleygwilliams** [comment]
@data-pup i used https://asciinema.org/ and then https://github.com/asciinema/asciicast2gif -- it is a SLOW process, and a little buggy, but a lot of fun- would love to see some more gifs!

**Comment by mgattozzi** [comment]
Yeah I'd say we could close this for now and I can open up more specific ones, like expanded tutorials, gifs etc. at a later date.

**Comment by data-pup** [comment]
Bandwidth is slightly thin for me at the moment, (focused on some `twiggy` stuff atm) but I would definitely be open to coming back to these in the near future. I think @mgattozzi is right, we could open issues for specific usage documentation tasks later on.

**Comment by mgattozzi** [comment]
Since all the original stuff mentioned was covered I'm going to close this then and open specific issues later.
