### ISSUE TITLE
use Cargo version of wasm-bindgen to better ensure not-broken build

### ISSUE THREAD

**Issue by aidanhs** [ashleygwilliams/wasm-pack#69]
Otherwise at the whims of whatever is on wasm-bindgen master, which bit us today.
<hr/>
*This is an issue reserved for someone who does not yet contribute to this repository.*

### MENTORSHIP INSTRUCTIONS:

Currently we install `wasm-bindgen` as a git dep. but we shouldn't! it's [published on Cargo now](https://crates.io/crates/wasm-bindgen)! change [these lines](https://github.com/ashleygwilliams/wasm-pack/blob/master/src/bindgen.rs#L13-L18) to run `cargo install wasm-bindgen` and not pass the `git` flag as we do right now. Feel free to ping me (@ag_dubs) on https://kiwiirc.com/client/irc.mozilla.org:+6667/#rust-wasm for help or any questions!

**Comment by ashleygwilliams** [comment]
@aidanhs how do u suppose we do this? (am genuinely unsure)

**Comment by ashleygwilliams** [comment]
oh! this still relies on a git dep of wasm-bindgen. boo. ok. i think the solution here is to just rely on the Cargo version. i can make a PR for this. i don't think @alexcritchon will be publishing a broken build and i want to rely on the release version anyways. thanks ya'll!

**Comment by ashleygwilliams** [comment]
(sorry for the confusion i was p certain that had been updated by a PR someone else sent it but i clearly did not review closely!)
