### ISSUE TITLE
document how to get rustfmt on nightly in "up and running"

### ISSUE THREAD

**Issue by ashleygwilliams** [ashleygwilliams/wasm-pack#72]
so- i originally put rustfmt in CI because i like enforcing style. however because this is on nightly and not yet stabilized the contributor experience is p poopy (cc @yoshuawuyts). thoughts on me ripping it out and just running it and commiting everyone once in a while? (this can make history really gross and i do love using git as a good history tool, but it might not be worth it at this point)

**Comment by yoshuawuyts** [comment]
yeah, still haven't fixed it yet, but haven't put in the time yet. I don't mind having development be nightly only for now. I don't mind if it stays tbh; it's def useful!

**Comment by sendilkumarn** [comment]
How about adding them in pre-push hooks?

And I do agree with @yoshuawuyts have it but don't worry about it.

**Comment by ashleygwilliams** [comment]
@sendilkumarn i think it would be just as frustrating as a pre-push hook, and a lot more to set up. i'll see what other contribs think (@mgattozzi has been bit by this so much, thankful for his patience), but sounds like we're should probably just keep it?

if someone wants to add a section to the current "up and running" section of the README about how to get cargo fmt setup correctly i would welcome a PR!

**Comment by mgattozzi** [comment]
@ashleygwilliams I personally don't mind. It's just a quick fix. It'd be nice if there was some kind of pre-push hook but you can't distribute those easily as part of a repo which has always seemed like a dumb move on git's part. I'm for keeping it to enforce style. We can always make it a part of the check list when submitting a PR by creating a template that GitHub can use.

**Comment by data-pup** [comment]
I can try and add some documentation for this, having just run into this myself. If it is worth anything, getting rustfmt working was not hard, and I didn't find it too bad as a new contributor :)

**Comment by mgattozzi** [comment]
Awesome! :D

**Comment by ashleygwilliams** [comment]
closed by #88
