### ISSUE TITLE
Replace quicli with only crates we need

### ISSUE THREAD

**Issue by mgattozzi** [ashleygwilliams/wasm-pack#89]
"I want to use quicli to quickly build CLI apps – And I want to stop there! If you are no longer writing a small CLI tool (I’d say something like 500 lines of code is no longer small), your problems are likely more complicated than what quicli gives you tools for." from [quicli - The ideas behind my small Rust CLI framework](https://deterministic.space/quicli.html)

We're over 500 and I think it gave us a good starting point to get this built up but as we expand features and logging we will need to be more selective of imports and we don't need everything from the prelude, which there was a `not used` warning I could not get rid of unless I imported some crates anyways. I think we should take what crates we need from quicli then fix up the code to work without it.

I have this on a wip bit of code whereby in `command.rs` I removed the `prelude` import to get rid of the warning during compilation. I had to import structopt derive into the crate as well for that to work.

Thoughts @ashleygwilliams?

**Comment by mgattozzi** [comment]
Let's tag this for a 0.4 release then and get 0.2 and 0.3 out.

**Comment by killercup** [comment]
Yes: Use quicli at your own risk from now on. Because you're at 606 LOC, I can no longer provide official support for your quicli usage.

Seriously though, I think you can quite easily eject from quicli. Remove to glob import (manually or using RLS if that works right now), and maybe use cargo-expand to get what the `main!` macros currently generates. The rest (if there is anything) is copypasta of small functions and `cargo add foo` calls.

**Comment by ashleygwilliams** [comment]
yup. but also: this is not a fire. it's not somehow coded in quicli that it becomes somehow not performant or not stable because we inched above 500 lines. we will of course refactor, but i want to reiterate that it is not urgent and is not currently causing us any issues.

**Comment by killercup** [comment]
Sure – but do let me know if you really want to get rid of those unnecessary deps and need help.

> it's not **[yet]** coded in quicli that it becomes somehow not performant or not stable because we inched above 500 lines.

😄
