### ISSUE TITLE
Will it be as awesome as Rusty parcel?

### ISSUE THREAD

**Issue by berkus** [ashleygwilliams/wasm-pack#92]
This is extremely awesome - https://github.com/parcel-bundler/parcel

It's in js/npm ecosystem, so if wasm-pack takes it as an aim to be like rusty parcel I will be extremely happy, so my question - is it realistic that wasm-pack takes parcel as a guiding bar level?

**Comment by ashleygwilliams** [comment]
hi @berkus !

we are also very impressed with parcel :) fundamentally, the problems that parcel solve vs the problems that wasm-pack will solve are slightly different but also somewhat similar. more specifically: parcel helps manage, bundle, and opitmize your client-side dependencies- wasm-pack, once we start handling dependencies declared in rust-generated wasm custom sections- will do SOME managing and optimization of your Rust dependency graph as well as any JS dependencies that those Rust dependencies might declare. 

to the end that they are a similar tool, we definitely aim to be as user-friendly and technically polished as parcel! if you have any specific features that you really enjoy about parcel, i'd love to hear them!

**Comment by berkus** [comment]
Happy to hear, will contribute by specifying some of my wishes as open issues after I play with wasm-pack a bit.

Thank you for driving this!
