### ISSUE TITLE
Declare a "main file" or index.js in the generated module

### ISSUE THREAD

**Issue by mstange** [ashleygwilliams/wasm-pack#94]
In the wasm-add example, the main JS file in the generated module is `wasm-add/wasm_add.js`. This means that you have to specify the JS filename when importing that module e.g. through webpack.

If the generated JS file were called `index.js` instead, or if its name was declared as the main file using [the `main` property in the module's package.json](https://docs.npmjs.com/files/package.json#main), one would be able to use just `import("wasm-add")` to import the module, which would be a bit nicer.

This would also allow the "test in your browser" button on the npm package site to work more smoothly. For example, if you click that button on [https://www.npmjs.com/package/@mgattozzi/wasm-add](https://www.npmjs.com/package/@mgattozzi/wasm-add), you get to [https://npm.runkit.com/@mgattozzi/wasm-add](https://npm.runkit.com/@mgattozzi/wasm-add), which says:

> `@mgattozzi/wasm-add` lists no main file and has no index.js, so it can't be directly required. If this is a mistake, please let us know. It may however contain internal files that you can require manually

**Comment by ashleygwilliams** [comment]
hey! so it would be pretty trivial to declare the file as `main` in the package.json and/or rename it. which do you prefer, i don't have a strong opinion. `index.js` is idiomatic. i'm tempted to do both! let me know what you think @mstange and we can get that done!

**Comment by mstange** [comment]
Sounds good!

My intuition would be to use `index.js` unless there's a good reason not to. And if you have an `index.js` I don't think you need a `main` in the package.json.

**Comment by mstange** [comment]
Thanks for fixing it so quickly! Also, wasm-pack is an awesome tool!

**Comment by mgattozzi** [comment]
Ohhh so that's why the es6 module require wasn't working. Thanks! :D
